version: "3.2"
networks:
  netaxe-network:
    driver: bridge
services:
# 前端
  micro-ipam-web:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-web:1.0
    build:
      context: .
      dockerfile: ./dockerfiles/web_dockerfile
    ports:
      - "9980:80"
    networks:
      - "netaxe-network"
    restart: always

  micro-ipam-backend:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-backend:05
    container_name: micro-ipam-backend
    ports:
      - "38005:18005"
      - "38055:35055"
    command: sh start.sh web
    volumes:
      - ./backend/IpamV1/conf.py:/home/ipam_backend/IpamV1/conf.py
      - ./backend/logs:/home/ipam_backend/logs
    networks:
      - "netaxe-network"
    
  micro-celery-ipam:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-backend:05
    container_name: micro-celery-ipam
    command: sh start.sh ipam
    volumes:
      - ./backend/IpamV1/conf.py:/home/ipam_backend/IpamV1/conf.py
      - ./backend/logs:/home/ipam_backend/logs
    networks:
      - "netaxe-network"
  micro-redis-cache:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/redis:latest
    container_name: micro-redis-cache
    ports:
      - "36379:6379"
    command: "redis-server --requirepass dade0f2a65237a56b79277e6dd27351d2854df033e0ad4b4f90abec229cd64df"
    networks:
      - "netaxe-network"