version: "3.2"
networks:
  ipam_network:
    ipam:
      config:
        - subnet: 192.168.253.0/24
services:
    # 后端入口
    ipam-backend:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-backend:1.0
      build:
          context: .
          dockerfile: ./dockerfiles/backend_dockerfile
      command: sh start.sh web
      networks:
          - "ipam_network"
      restart: always

    # nginx代理
    ipam-backend-nginx:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-backend-nginx:1.23.1
      build:
        context: .
        dockerfile: ./dockerfiles/nginx_dockerfile
      networks:
        - "ipam_network"
      ports:
        - "31105:80"

    # 前端
    ipam-web:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-web:1.0
      build:
        context: .
        dockerfile: ./dockerfiles/web_dockerfile
      ports:
        - "9905:80"
      networks:
        - "ipam_network"
      restart: always