version: "3.7"
services:
    # 后端入口
    ipam-single-backend:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-single-backend:1.0
      build:
          context: .
          dockerfile: ./dockerfiles/backend_dockerfile
      command: sh single-init.sh
      restart: always

    # nginx代理
    ipam-single-backend-nginx:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-single-backend-nginx:1.23.1
      build:
          context: .
          dockerfile: ./dockerfiles/single_nginx_dockerfile
      ports:
          - "31113:80"

    # 前端
    ipam-single-web:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-single-web:1.0
      build:
          context: .
          dockerfile: ./dockerfiles/single_web_dockerfile
      ports:
          - "32092:80"
      restart: always

    single-mysql-server:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/mysql:5.7
      restart: always
      container_name: single-mysql-server
      environment:
        TZ: Asia/Shanghai
        MYSQL_DATABASE: "ipam"
        MYSQL_USER: "netaxe"
        MYSQL_ROOT_PASSWORD: "root_devnet@2022"
      volumes:
        - ./my.cnf:/etc/mysql/my.cnf
        - ./mysql_data:/var/lib/mysql
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
      ports:
        - "38306:3306"
